Repository adobecom/cc, pull requests merged in 2024-05, with the labels that each got.

#283 MWPW-147501 | Changing CSS for blue focus line to cover the whole div
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
Labels: verified, ready for stage

#285 MWPW-147361-Update firefly model to v3
  creativecloud/features/firefly/firefly-susi.js
Labels: verified, ready for stage

#284 MWPW-146794 | Avoid CLS due to image
  creativecloud/blocks/interactive-marquee/milo-marquee.css
Labels: verified

#281 MWPW-142971 | Add new workflow for generate->select->startover
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
Labels: verified

#287 MWPW-147649 | Resync stage and main, reopening stage PRs
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/firefly/firefly-susi.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
  test/blocks/sidenav/mocks/blah.svg
  test/blocks/sidenav/sidenav.test.html
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified

#288 [Release] Sync main from stage 2/5/2024
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/firefly/firefly-susi.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
  test/blocks/sidenav/mocks/blah.svg
  test/blocks/sidenav/sidenav.test.html
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified

#280 MWPW-142989-Multi image marquee
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/features/firefly/firefly-interactive.js
  creativecloud/features/firefly/firefly-masonry.css
  creativecloud/features/firefly/firefly-masonry.js
  creativecloud/features/interactive-elements/interactive-elements.js
  creativecloud/scripts/utils.js
  test/features/firefly/firefly-masonry-autocycle.test.js
  test/features/firefly/firefly-masonry.test.js
  test/features/firefly/mocks/masonry-body.html
Labels: verified, ready for stage

#290 MWPW-147905-Move image span value outside of alt value
  creativecloud/features/firefly/firefly-masonry.js
Labels: verified

#291 Continue to Photoshop button added on Hue-Sat marquee.
  creativecloud/deps/openInPsWeb/e2bb343a.js
  creativecloud/deps/openInPsWeb/openInPsWeb.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
  creativecloud/scripts/scripts.js
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#293 MWPW-148147-Fix Generate button
  creativecloud/features/firefly/firefly-masonry.js
Labels: verified, ready for stage

#296 [Release] Sync main from stage 5/14
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/deps/openInPsWeb/e2bb343a.js
  creativecloud/deps/openInPsWeb/openInPsWeb.js
  creativecloud/features/firefly/firefly-interactive.js
  creativecloud/features/firefly/firefly-masonry.css
  creativecloud/features/firefly/firefly-masonry.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
  creativecloud/features/interactive-elements/interactive-elements.js
  creativecloud/scripts/scripts.js
  creativecloud/scripts/utils.js
  test/features/firefly/firefly-masonry-autocycle.test.js
  test/features/firefly/firefly-masonry.test.js
  test/features/firefly/mocks/masonry-body.html
Labels: verified

#301 [MWPW-147521] interactive marquee container is not seen displayed as expected with resize flow
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/genfill/genfill-interactive.css
  creativecloud/features/interactive-elements/interactive-elements.css
Labels: bug, verified, ready for stage

#302 MWPW-148223 & MWPW-148222 | Kodiak vulnerable package due to different versions of same package. (#302)
  package.json
Labels: ready for stage
