Repository adobecom/cc, pull requests merged in 2024-03, with the labels that each got.

#195 MWPW-143533-Handle css for 2 values in selector tray
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/firefly/firefly-interactive.js
Labels: verified

#199 MWPW-143631-Add cis_ru to locales
  creativecloud/scripts/scripts.js
Labels: verified

#200 [Main]MWPW-143631-Add cis_ru to locales
  creativecloud/scripts/scripts.js
Labels: verified

#203 MWPW-140666: add cis_en to locales
  creativecloud/scripts/scripts.js
Labels: trivial, verified

#210 MWPW-143426 fixing sidenav parents when implicitly declared
  creativecloud/blocks/sidenav/sidenav.js
  test/blocks/sidenav/sidenav.test.html
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified

#220 MWPW-142577-Update all media paths to load from content root
  creativecloud/scripts/utils.js
Labels: needs verification

#222 MWPW-144477-Fix selector tray alignment
  creativecloud/features/firefly/firefly-interactive.css
Labels: verified, ready for main

#223 MWPW-143057-Remove mt and cy_en from CC sitemap
  creativecloud/sitemap-index.xml
  helix-query.yaml
  helix-sitemap.yaml
Labels: trivial, ready for main

#231 MWPW-144599-Include /ai/** path in sitemap
  helix-query.yaml
Labels: trivial

#225 MWPW 144479 | Improve performance and reduce CLS for interactive marquee
  creativecloud/scripts/utils.js
Labels: verified

#230 MWPW-144525 | Fixing the code coverage plugin path
  codecov.yaml
  package.json
  web-test-runner.config.mjs
Labels: ready for main

#237 MWPW 144479 | Improve performance and reduce CLS for interactive marquee
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#242 [Release] Sync main from stage 20/3/2024
  creativecloud/scripts/utils.js
Labels: verified

#250 MWPW-145307- Move enticement text to p tag
  creativecloud/features/genfill/genfill-interactive.css
  creativecloud/features/interactive-elements/interactive-elements.css
  creativecloud/features/interactive-elements/interactive-elements.js
Labels: verified, ready for main

#219 [MWPW-143093]-[Interactive Marquee - Media] Rename media classname to avoid collisions
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/firefly/firefly-interactive.js
  creativecloud/features/genfill/genfill-interactive.css
  creativecloud/features/genfill/genfill-interactive.js
Labels: verified, ready for stage
