Repository adobecom/cc, pull requests merged in 2024-10, with the labels that each got.

#421 MWPW-159417-Update stage domain mapping
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#424 MWPW-159304- Remove Extra Spacing Under CTA in Marquee Component (Mobile & Tablet)
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
Labels: verified, ready for stage

#412 MWPW-158911: Unable to scroll page if the filters modal closed by click outside of the modal
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified, ready for stage

#430 MWPW-159423: Link urls are not resolved on Main Milo catalog and give 404
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#431 MWPW-155686 Catalog Milo: Preview Index Follow Up
  .github/workflows/run-preview-index-single.yaml
Labels: verified, ready for stage

#432 [MWPW-159710] Remove parameter on milo:deferred event
  creativecloud/blocks/universal-promo-terms/universal-promo-terms.css
  creativecloud/blocks/universal-promo-terms/universal-promo-terms.js
Labels: verified, ready for stage, High Priority

#436 MWPW-159137-Sitemap for batch 27
  helix-query.yaml
Labels: trivial, verified, ready for stage
