Repository adobecom/cc, pull requests merged in 2024-09, with the labels that each got.

#390 MWPW-153411 | Changing highlight state
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
  test/features/interactive-components/selector-tray/selector-tray.test.js
Labels: verified, ready for stage

#401 MWPW-147305 Adding generative pattern label to generate bar on Interactive Marquee
  creativecloud/features/interactive-components/generate/generate.css
  creativecloud/features/interactive-components/generate/generate.js
  test/features/interactive-components/generate/mocks/body.html
Labels: verified, ready for stage

#400 Revert "MWPW-156262 flip sidenav and merch-collection order (#392)"
  creativecloud/blocks/catalog/catalog.js
Labels: verified, commerce, ready for stage

#404 MWPW-157468 flipping again sidenav and collection
  creativecloud/blocks/catalog/catalog.js
Labels: verified, ready for stage

#398 [MWPW-152487] Promo term update
  creativecloud/blocks/universal-promo-terms/universal-promo-terms.js
Labels: verified, ready for stage, High Priority

#406 MWPW-156788: Unable to scroll page with active Sort filter
  creativecloud/deps/merch-sidenav.js
Labels: verified, ready for stage

#408 MWPW-155820 | Reducing the selector tray icon size to 80x80
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
  test/blocks/interactive-metadata/interactive-metadata.test.js
Labels: trivial, verified, ready for stage

#407 MWPW-158147-Eager load hero marque foreground image
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#411 [MWPW-158444] Added stage domains map
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#413 MWPW-159014 | Video handling for premiere
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
Labels: verified, ready for stage

#417 [MWPW-159151] Rearrange content in mobile view for marquee used with interactive metadata
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
Labels: verified, ready for stage

#418 Revert "[Test]Update README.md"
  README.md
Labels: trivial

#420 MWPW-159309 | Unit test fix
  test/scripts/mocks/head.html
  test/scripts/scripts.test.js
Labels: verified, ready for stage

#419 [Release] Stage to Main 09/27
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
  test/scripts/mocks/head.html
  test/scripts/scripts.test.js
Labels: verified, ready for main
