Repository adobecom/cc, pull requests merged in 2024-06, with the labels that each got.

#312 MWPW-151448 | Fixing dot media issue in locale
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#317 MWPW-148028 | Change bg remove launch load in deps js
  creativecloud/deps/interactive-marquee-changebg/changeBgMarquee.js
Labels: verified, ready for stage

#307 Various catalog related fixes
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  package-lock.json
  package.json
  web-test-runner.config.mjs
Labels: verified, ready for stage

#332 [Release] Sync main from stage 6/6
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/interactive-marquee-changebg/changeBgMarquee.js
  creativecloud/deps/merch-sidenav.js
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/genfill/genfill-interactive.css
  creativecloud/features/interactive-elements/interactive-elements.css
  creativecloud/scripts/utils.js
  package-lock.json
  package.json
  web-test-runner.config.mjs
Labels: verified, ready for main

#303 MWPW-148162: 'Upload an image' button alignment is not proper for hue sat after localisation
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
Labels: verified, ready for stage

#320 MWPW-151642: Repo Sync Workflow for FG
  .github/workflows/fg-sync-repos.yml
Labels: ready for stage

#329 MWPW-140115 Release notes on slack channel when PR merged with Main branch
  .github/workflows/merged-to-main.yaml
  .github/workflows/src/helpers.js
  .github/workflows/src/send-slack.js
Labels: verified

#321 acomsis cookie logic for cn homepage
  creativecloud/scripts/scripts.js
  creativecloud/scripts/utils.js
Labels: ready for stage

#334 MWPW-130601-Add typekit for adobe clean thai
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#337 Fixing infinity reload bug
  creativecloud/scripts/utils.js
Labels: ready for stage

#338 [Release] Sync main from stage 6/11
  .github/workflows/fg-sync-repos.yml
  .github/workflows/merged-to-main.yaml
  .github/workflows/src/helpers.js
  .github/workflows/src/send-slack.js
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
  creativecloud/scripts/scripts.js
  creativecloud/scripts/utils.js
Labels: verified

#341 MWPW-152553- Include new paths for indexing
  helix-query.yaml
Labels: High Priority

#346 MWPW-153428-Eager load marquee background image only for current breakpoint
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#343 MWPW-148256 decorate catalog cards & some sidenav with analytics attributes
  creativecloud/blocks/catalog/catalog.js
  creativecloud/blocks/sidenav/sidenav.js
Labels: verified, commerce, ready for stage
