Repository adobecom/cc, pull requests merged in 2024-04, with the labels that each got.

#255 MWPW-142577 | Load media from cc-shared for root
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#256 [Release] Sync main from stage 1/4/2024
  .kodiak/config.yaml
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/features/firefly/firefly-interactive.css
  creativecloud/features/firefly/firefly-interactive.js
  creativecloud/features/genfill/genfill-interactive.css
  creativecloud/features/genfill/genfill-interactive.js
  creativecloud/features/interactive-elements/interactive-elements.css
  creativecloud/features/interactive-elements/interactive-elements.js
  creativecloud/scripts/utils.js
Labels: verified

#259 [Release] Sync main from stage 2/4/2024
  .github/pull_request_template.md
  tools/sidekick/config.json
Labels: verified

#253 @releng better hlxignore
  .hlxignore
Labels: verified, run-nala, ready for stage

#257 [MWPW-145840] Enticement position is not proper for RTL locale in page and fragment -- fixed
  creativecloud/features/genfill/genfill-interactive.css
Labels: verified, ready for stage

#251 MWPW-142971 | Interactive web components over Marquee and Aside
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/features/interactive-components/crop/crop.css
  creativecloud/features/interactive-components/crop/crop.js
  creativecloud/features/interactive-components/generate/generate.css
  creativecloud/features/interactive-components/generate/generate.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
  creativecloud/features/interactive-components/start-over/start-over.css
  creativecloud/features/interactive-components/start-over/start-over.js
  creativecloud/scripts/utils.js
  creativecloud/styles/styles.css
  test/blocks/interactive-metadata/interactive-metadata.test.js
  test/blocks/interactive-metadata/mocks/assets/icon_.svg
  test/blocks/interactive-metadata/mocks/assets/media_.png
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/interactive-components/crop/crop.test.js
  test/features/interactive-components/crop/mocks/body.html
  test/features/interactive-components/generate/generate.test.js
  test/features/interactive-components/generate/mocks/body.html
  test/features/interactive-components/selector-tray/mocks/body.html
  test/features/interactive-components/selector-tray/selector-tray.test.js
  test/features/interactive-components/slider-tray/mocks/body.html
  test/features/interactive-components/slider-tray/slider-tray.test.js
  test/features/interactive-components/start-over/mocks/body.html
  test/features/interactive-components/start-over/start-over.test.js
Labels: verified

#261 MWPW-146221 | Improving performance for hue sat
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
Labels: verified, ready for stage

#264 MWPW-146229 | Integrating review comments and new workflows
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/features/interactive-components/crop/crop.js
  creativecloud/features/interactive-components/generate/generate.css
  creativecloud/features/interactive-components/generate/generate.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
  creativecloud/features/interactive-components/start-over/start-over.css
  test/blocks/interactive-metadata/interactive-metadata.test.js
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/interactive-components/crop/mocks/body.html
  test/features/interactive-components/generate/mocks/body.html
  test/features/interactive-components/selector-tray/mocks/body.html
  test/features/interactive-components/start-over/mocks/body.html
Labels: verified, ready for stage

#263 MWPW-142006 - Enable repo-sync for graybox
  .github/workflows/graybox-sync-repos.yml
Labels: ready for stage

#246 MWPW-143951: Optimize sidenav
  creativecloud/blocks/catalog/catalog.css
  creativecloud/blocks/catalog/catalog.js
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  creativecloud/scripts/scripts.js
Labels: verified, commerce, ready for stage

#265 [hue saturation] upload image icon authored is not seen visible in mobile mode
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
Labels: verified, ready for stage

#266 [Release] Sync main from stage 11/4/2024
  .github/workflows/graybox-sync-repos.yml
  .hlxignore
  creativecloud/blocks/catalog/catalog.css
  creativecloud/blocks/catalog/catalog.js
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  creativecloud/features/genfill/genfill-interactive.css
  creativecloud/features/interactive-components/crop/crop.css
  creativecloud/features/interactive-components/crop/crop.js
  creativecloud/features/interactive-components/generate/generate.css
  creativecloud/features/interactive-components/generate/generate.js
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
  creativecloud/features/interactive-components/slider-tray/slider-tray.css
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
  creativecloud/features/interactive-components/start-over/start-over.css
  creativecloud/features/interactive-components/start-over/start-over.js
  creativecloud/scripts/scripts.js
  creativecloud/scripts/utils.js
  creativecloud/styles/styles.css
  test/blocks/interactive-metadata/interactive-metadata.test.js
  test/blocks/interactive-metadata/mocks/assets/icon_.svg
  test/blocks/interactive-metadata/mocks/assets/media_.png
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/interactive-components/crop/crop.test.js
  test/features/interactive-components/crop/mocks/body.html
  test/features/interactive-components/generate/generate.test.js
  test/features/interactive-components/generate/mocks/body.html
  test/features/interactive-components/selector-tray/mocks/body.html
  test/features/interactive-components/selector-tray/selector-tray.test.js
  test/features/interactive-components/slider-tray/mocks/body.html
  test/features/interactive-components/slider-tray/slider-tray.test.js
  test/features/interactive-components/start-over/mocks/body.html
  test/features/interactive-components/start-over/start-over.test.js
Labels: verified

#269 MWPW-144519 | Increasing unit test coverage
  test/blocks/changeBg/changeBg.test.js
  test/blocks/interactive-marquee/interactive-marquee.test.js
  test/blocks/interactive-marquee/mocks/body.html
  test/blocks/interactive-marquee/mocks/container.html
  test/features/changeBg/changeBg.test.js
  test/features/changeBg/mocks/body.html
  test/features/firefly/firefly-interactive.test.js
  test/features/firefly/mocks/body.html
  test/features/genfill/genfill-interactive.test.js
  test/features/genfill/mocks/genfill.html
  test/features/interactive-components/start-over/mocks/body.html
  test/features/interactive-components/start-over/start-over.test.js
  test/scripts/decorate.test.js
  test/scripts/mocks/body.html
  test/scripts/scripts.test.js
Labels: trivial, verified, ready for stage

#267 MWPW-142972 | Integrating review comments
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/features/interactive-components/start-over/start-over.js
Labels: verified, ready for stage

#270 [Release] Sync main from stage 17/4/2024
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
  creativecloud/features/interactive-components/start-over/start-over.js
  test/blocks/changeBg/changeBg.test.js
  test/blocks/interactive-marquee/interactive-marquee.test.js
  test/blocks/interactive-marquee/mocks/body.html
  test/blocks/interactive-marquee/mocks/container.html
  test/features/changeBg/changeBg.test.js
  test/features/changeBg/mocks/body.html
  test/features/firefly/firefly-interactive.test.js
  test/features/firefly/mocks/body.html
  test/features/genfill/genfill-interactive.test.js
  test/features/genfill/mocks/genfill.html
  test/features/interactive-components/start-over/mocks/body.html
  test/features/interactive-components/start-over/start-over.test.js
  test/scripts/decorate.test.js
  test/scripts/mocks/body.html
  test/scripts/scripts.test.js
Labels: verified, ready for main

#271 MWPW-143904-New block: cc-mobile-app-banner
  creativecloud/blocks/cc-mobile-app-banner/cc-mobile-app-banner.css
  creativecloud/blocks/cc-mobile-app-banner/cc-mobile-app-banner.js
  creativecloud/scripts/utils.js
  test/blocks/cc-mobile-app-banner/cc-mobile-app-banner.test.js
  test/blocks/cc-mobile-app-banner/mocks/body.html
  test/blocks/cc-mobile-app-banner/mocks/branch-io-key.json
  test/helpers/waitForElement.js
Labels: verified

#273 Revert "MWPW-143904-New block: cc-mobile-app-banner"
  creativecloud/blocks/cc-mobile-app-banner/cc-mobile-app-banner.css
  creativecloud/blocks/cc-mobile-app-banner/cc-mobile-app-banner.js
  creativecloud/scripts/utils.js
  test/blocks/cc-mobile-app-banner/cc-mobile-app-banner.test.js
  test/blocks/cc-mobile-app-banner/mocks/body.html
  test/blocks/cc-mobile-app-banner/mocks/branch-io-key.json
  test/helpers/waitForElement.js
Labels: verified

#274 DOTCOM-118347
  creativecloud/scripts/scripts.js
Labels: needs verification

#276 Feat(MWPW-145612):CTA's of interactive marquee moved above the fold.
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-marquee/milo-marquee.css
  creativecloud/features/firefly/firefly-interactive.css
Labels: verified, ready for stage

#277 Revert "DOTCOM-118347" as it is not verified and has issues
  creativecloud/scripts/scripts.js
Labels: verified

#254 MWPW-143894, MWPW-142148 sidenav authoring enhancements
  creativecloud/blocks/sidenav/sidenav.js
  test/blocks/sidenav/mocks/blah.svg
  test/blocks/sidenav/sidenav.test.html
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified, commerce, ready for stage
