Repository adobecom/cc, pull requests merged in 2024-08, with the labels that each got.

#372 [MWPW-153994] Update helix query for sitemaps - Batch 00C
  helix-query.yaml
Labels: verified, ready for stage

#379 MWPW-154549 | Integrating unity Block in CC
  creativecloud/blocks/unity/unity.css
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/scripts.js
Labels: verified

#374 MWPW-153405 | Changing the selector tray thumbnail size
  creativecloud/features/interactive-components/selector-tray/selector-tray.css
Labels: verified, ready for stage

#368 MWPW-154124: Preview resources index - for merch-collections & Catalog go live
  .github/preview-index/.npmrc
  .github/preview-index/README.md
  .github/preview-index/package-lock.json
  .github/preview-index/package.json
  .github/preview-index/src/update.js
  .github/workflows/run-preview-index.yaml
  .gitignore
Labels: verified, ready for stage

#382 MWPW-155908 Support hero-marquee eager loading of images in cc
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#377 MWPW-155183 - Add new workflow to support premiere pro page
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
Labels: verified, ready for stage

#381 MWPW-155431 - Don't convert adobe.com urls to stage.adobe.com url
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#385 Revert "MWPW-154549 | Integrating unity Block in CC"
  creativecloud/blocks/unity/unity.css
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/scripts.js
Labels: verified

#386 MWPW-154549 | Integrating unity Block in CC
  creativecloud/blocks/unity/unity.css
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/scripts.js
Labels: verified

#388 [MWPW-155626] Add paths for batch20 to sitemap
  helix-query.yaml
Labels: trivial, verified, ready for stage

#389 MWPW-155686 Catalog Milo: Preview Index Follow Up
  .github/preview-index/package.json
  .github/preview-index/src/testevent.js
  .github/workflows/run-preview-index-test.yaml
Labels: verified, ready for stage

#384 Fix(MWPW-156143):The action is scheduled to run from Monday through Thursday.
  .github/workflows/merge-to-stage.yaml
Labels: verified, ready for stage

#392 MWPW-156262 flip sidenav and merch-collection order
  creativecloud/blocks/catalog/catalog.js
Labels: verified, ready for stage

#391 MWPW-155686 Catalog Milo: Preview Index Follow Up
  .github/preview-index/README.md
  .github/preview-index/package.json
  .github/preview-index/src/indexFull.js
  .github/preview-index/src/indexSingle.js
  .github/preview-index/src/sharepoint.js
  .github/preview-index/src/testevent.js
  .github/preview-index/src/update.js
  .github/workflows/run-preview-index-single.yaml
  .github/workflows/run-preview-index.yaml
Labels: verified, ready for stage

#393 [MWPW-156809] add alt text for placeholder image
  creativecloud/blocks/interactive-metadata/interactive-metadata.js
Labels: verified, ready for stage

#394 [MWPW-155675] Button position fixed in RTL Locale in iPad in interactive elements
  creativecloud/features/interactive-components/generate/generate.css
Labels: bug, verified, ready for stage

#397 fix(MWPW-156308):Interactive marquee slider tray Accessibility fix.
  creativecloud/features/interactive-components/slider-tray/slider-tray.js
Labels: verified, ready for stage

#399 MWPW-155686 Catalog Milo: Preview Index Follow Up
  .github/preview-index/src/indexFull.js
  .github/preview-index/src/indexSingle.js
  .github/preview-index/src/sharepoint.js
Labels: verified, ready for stage
