Repository adobecom/cc, pull requests merged in 2024-01, with the labels that each got.

#151 [MWPW-140669][Milo - Interactive marquee] missed specs from Figma file #2, #3 and #4
  creativecloud/blocks/interactive-marquee/interactive-marquee.js
  creativecloud/blocks/interactive-marquee/milo-marquee.css
Labels: verified

#164 Delete web-test-runner-config.mjs
  web-test-runner-config.mjs
Labels: run-nala

#166 MWPW-138378-Update sitemap-index.xml to add new geos for 1C ROW
  creativecloud/sitemap-index.xml
Labels: do not merge
