Repository adobecom/cc, pull requests merged in 2024-07, with the labels that each got.

#345 MWPW-153144 Pre-load Marquee image if the marquee is getting replaced in MEP
  creativecloud/scripts/utils.js
Labels: ready for stage

#331 Update config.json
  tools/sidekick/config.json
Labels: verified, ready for stage

#347 fix(MWPW-152365):reading width increased.
  creativecloud/styles/styles.css
Labels: verified, ready for stage

#350 MWPW-153144 | Fix issue in utils check queryselector
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#348 MWPW-140115 Release notes on slack channel when PR merged with Main branch
  .github/workflows/merged-to-main.yaml
  .github/workflows/src/helpers.js
  .github/workflows/src/send-slack.js
  package-lock.json
  package.json
Labels: verified, ready for stage

#349 [Release] Sync main from stage 7/9
  .github/workflows/merged-to-main.yaml
  .github/workflows/src/helpers.js
  .github/workflows/src/send-slack.js
  creativecloud/blocks/catalog/catalog.js
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/scripts/utils.js
  creativecloud/styles/styles.css
  package-lock.json
  package.json
  tools/sidekick/config.json
Labels: verified, ready for main

#353 OPT-27991 AEXG4866 - AX take over of FF T2i SEO page
  creativecloud/scripts/mep/aexg4866/firefly/firefly-masonry.js
  creativecloud/scripts/mep/aexg4866/interactive-marquee/interactive-marquee.css
  creativecloud/scripts/mep/aexg4866/interactive-marquee/interactive-marquee.js
Labels: trivial, verified, ready for stage

#354 OPT-27991 AEXG4866 - AX take over of FF T2i SEO page - FIXES
  creativecloud/scripts/mep/aexg4866/firefly/firefly-masonry.js
Labels: trivial

#351 MWPW-147481 | Enable configurable prompt for generate after select step
  creativecloud/features/interactive-components/generate/generate.js
Labels: enhancement, verified, ready for stage

#352 [MWPW-154272]: Eager Loading only one image for each viewport
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#335 MWPW-147716: Disabled background scroll for filter dialog
  creativecloud/deps/merch-sidenav.js
Labels: verified, ready for stage

#358 [Release] Sync main from stage 7/22
  creativecloud/deps/merch-sidenav.js
  creativecloud/features/interactive-components/generate/generate.js
  creativecloud/scripts/utils.js
Labels: verified, ready for main

#357 MWPW-154660 - remove marTechUrl and edgeConfigId for performance improvements
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#361 MWPW-154549 | Integrating unity Block in CC
  creativecloud/blocks/unity/unity.css
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/scripts.js
Labels: verified

#360 https://jira.corp.adobe.com/browse/MWPW-148229 -Milo Catalog Batch00d - Left Rail filter hover Text
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified, ready for stage

#362 [MWPW 151457] Added stage domains map to make links environment-aware
  creativecloud/scripts/scripts.js
Labels: verified, ready for stage

#359 [MWPW-154422] generate button is seen moved out of the screen in ipad - bug fix
  creativecloud/features/interactive-components/generate/generate.css
Labels: bug, verified, ready for stage

#365 MWPW-144603 - Update path in helix query for sitemap
  helix-query.yaml
Labels: trivial, ready for stage

#366 [Release] Sync main from stage 7/26
  .github/workflows/merge-to-stage.js
  .github/workflows/merge-to-stage.yaml
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  creativecloud/features/interactive-components/generate/generate.css
  creativecloud/scripts/scripts.js
  helix-query.yaml
  test/blocks/sidenav/sidenav.test.html.js
Labels: verified, ready for main

#369 MWPW-154549 | Integrating unity Block in CC
  creativecloud/blocks/unity/unity.css
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/scripts.js
Labels: verified

#364 MWPW-153245 [catalog] analytics fixes
  creativecloud/blocks/catalog/catalog.js
  creativecloud/blocks/sidenav/sidenav.js
  creativecloud/deps/merch-sidenav.js
  test/blocks/catalog/catalog.test.html
  test/blocks/catalog/catalog.test.html.js
Labels: verified, commerce, ready for stage
