Repository adobecom/cc, pull requests merged in 2025-03, with the labels that each got.

#661 Revert "MWPW-157950 | Migrating CC to unity V2 for performance and flexibility"
  creativecloud/blocks/unity/unity.js
Labels: ready for stage

#662 MWPW-157950 | Migrating CC to unity V2 for performance and flexibility
  creativecloud/blocks/unity/unity.js
Labels: ready for stage, verify on stage

#659 MWPW-168445- Exclude genuine urls from transforming based on environment
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#654 MWPW-160311-Fix CMR automation
  .github/workflows/servicenow.py
  .github/workflows/servicenow.yaml
Labels: verified, ready for stage

#655 Fix(mwpw-154971): Updated type kit.
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#650 MWPW-166688: [Milo Plans Page] Category Filters for Plans page - contrast adjustments
  creativecloud/blocks/sidenav/sidenav.css
Labels: verified, ready for stage

#664 [Release] Stage to Main 03/06
  .github/workflows/servicenow.py
  .github/workflows/servicenow.yaml
  creativecloud/features/cc-forms/components/textfield.js
  creativecloud/scripts/utils.js
Labels: verified, ready for main

#668 MWPW-166688: [Milo Plans Page] Category Filters for Plans page - contrast adjustments
  creativecloud/blocks/sidenav/sidenav.css
Labels: verified, ready for stage

#666 MWPW-157950 | Migrating CC to unity V2 for performance and flexibility
  creativecloud/blocks/unity/unity.js
Labels: verify on stage

#670 Revert | MWPW-154971 | Updated type kit.
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#672 Revert "MWPW-157950 | Migrating CC to unity V2 for performance and flexibility"
  creativecloud/blocks/unity/unity.js
Labels: verified, ready for stage

#673 Revert "MWPW-166688: [Milo Plans Page] Category Filters for Plans page - contrast adjustments"
  creativecloud/blocks/sidenav/sidenav.css
Labels: verified, ready for stage

#674 [Release] Stage to Main 03/06 | Urgent revert typekit change
  creativecloud/scripts/utils.js
Labels: verified, ready for main

#675 MWPW-166688: [Milo Plans Page] Category Filters for Plans page - contrast adjustments
  creativecloud/blocks/sidenav/sidenav.css
Labels: ready for stage, release-remerge

#676 MWPW-157950 | Migrating CC to unity V2 for performance and flexibility
  creativecloud/blocks/unity/unity.js
Labels: ready for stage, release-remerge

#663 MWPW-165739 | Sitemap update for DALP batch [1]
  helix-query.yaml
Labels: verified, verify on stage

#679 MWPW-167457 | Localized odin urls for dropdowns
  creativecloud/features/cc-forms/components/dropdown.js
Labels: verified, ready for stage, verify on stage

#686 MWPW-169714-Update to point links in .live page prod instead of stage
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#684 MWPW-170191 - New unity upload block
  creativecloud/blocks/upload/upload.css
  creativecloud/blocks/upload/upload.js
  test/blocks/upload/mocks/body.html
  test/blocks/upload/upload.test.js
Labels: verified
