Repository adobecom/cc, pull requests merged in 2025-02, with the labels that each got.

#593 [MWPW-166392] Zip/postal code validation pattern
  creativecloud/features/cc-forms/components/textfield.js
Labels: verified, ready for stage

#600 MWPW-165982 | Load and render fix
  creativecloud/blocks/cc-forms/cc-forms.js
  creativecloud/features/cc-forms/components/dropdown.js
  creativecloud/features/cc-forms/forms/trials.js
  test/blocks/cc-forms/cc-forms.test.js
  test/blocks/cc-forms/mocks/body.html
  test/features/cc-forms/components/dropdown.test.js
  test/features/cc-forms/forms/demandbase.test.js
  test/features/cc-forms/forms/mocks/perpeptual-body.html
  test/features/cc-forms/forms/perpeptual.test.js
  test/features/cc-forms/forms/trials.test.js
Labels: verified, ready for stage

#604 MWPW-165982 | Adding more unit tests for perpeptual coverage
  test/blocks/cc-forms/cc-forms.test.js
  test/blocks/cc-forms/mocks/body.html
  test/features/cc-forms/forms/mocks/perpeptual-body.html
  test/features/cc-forms/forms/perpeptual.test.js
Labels: verified, ready for stage

#594 [MWPW-166856] [Forms-demandbase] Prepopulate select fields correctly
  creativecloud/blocks/cc-forms/cc-forms.js
  creativecloud/features/cc-forms/forms/demandbase.js
Labels: verified, ready for stage

#484 Support both .aem. and .hlx. - HLX5 Support
  .github/preview-index/README.md
  .github/preview-index/src/indexFull.js
  .github/preview-index/src/sharepoint.js
  .github/pull_request_template.md
  .github/workflows/merge-to-stage.js
  creativecloud/blocks/unity/unity.js
  creativecloud/features/changeBg/changeBg.js
  creativecloud/scripts/utils.js
  libs/deps/README
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/firefly/mocks/body.html
  test/features/firefly/mocks/masonry-body.html
  tools/sidekick/config.json
  web-test-runner.config.mjs
Labels: verified, ready for stage, High Priority

#613 Fix(MWPW-167586): Helix upgrade fix.
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#611 [MWPW-167281] 'state' field is empty and unclickable when we change the org name in the form for mobile
  creativecloud/features/cc-forms/forms/demandbase.js
Labels: bug, verified, ready for stage

#608 MWPW-166067 : Error message is not seen popuplating in iphone on connect forms working in desktop and android
  creativecloud/blocks/cc-forms/cc-forms.js
  creativecloud/features/cc-forms/components/checkbox.js
  creativecloud/features/cc-forms/components/dropdown.js
  creativecloud/features/cc-forms/components/textfield.js
  creativecloud/features/cc-forms/forms/trials.js
Labels: verified, ready for stage

#605 Stop CMR creation in github workflow for
  .github/workflows/servicenow.yaml
Labels: verified, ready for stage

#619 Revert "Fix(MWPW-167586): Helix upgrade fix."
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#620 Revert "Support both .aem. and .hlx. - HLX5 Support"
  .github/preview-index/README.md
  .github/preview-index/src/indexFull.js
  .github/preview-index/src/sharepoint.js
  .github/pull_request_template.md
  .github/workflows/merge-to-stage.js
  creativecloud/blocks/unity/unity.js
  creativecloud/features/changeBg/changeBg.js
  creativecloud/scripts/utils.js
  libs/deps/README
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/firefly/mocks/body.html
  test/features/firefly/mocks/masonry-body.html
  tools/sidekick/config.json
  web-test-runner.config.mjs
Labels: verified, ready for stage

#618 MWPW-167101 [Connect]Numbers are getting accepted in the name filed
  creativecloud/features/cc-forms/components/textfield.js
Labels: verified, ready for stage

#621 Support both .aem. and .hlx. - HLX5 Support
  .github/preview-index/README.md
  .github/preview-index/src/indexFull.js
  .github/preview-index/src/sharepoint.js
  .github/pull_request_template.md
  .github/workflows/merge-to-stage.js
  creativecloud/blocks/unity/unity.js
  creativecloud/features/changeBg/changeBg.js
  creativecloud/scripts/utils.js
  libs/deps/README
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/firefly/mocks/body.html
  test/features/firefly/mocks/masonry-body.html
  tools/sidekick/config.json
  web-test-runner.config.mjs
Labels: verified, ready for stage

#622 MWPW-167586 | Helix upgrade fix
  creativecloud/blocks/unity/unity.js
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#629 MWPW-168029 | Correct error page for forms error
  creativecloud/features/cc-forms/forms/trials.js
Labels: verified, ready for stage

#627 [MWPW-166069] fix checkbox alignment in cc forms
  creativecloud/blocks/cc-forms/cc-forms.css
Labels: verified, ready for stage

#628 reverting the config file to support localization
  tools/sidekick/config.json
Labels: verified, ready for stage

#641 [MWPW-166069] fix checkbox alignment in cc forms
  creativecloud/blocks/cc-forms/cc-forms.css
Labels: verified, ready for stage

#639 [Connect]Numbers are getting accepted in the name filed""
  creativecloud/features/cc-forms/components/textfield.js
Labels: verified, ready for stage

#640 MWPW-168029 | Correct error page for forms error
  creativecloud/features/cc-forms/forms/trials.js
Labels: verified, ready for stage

#643 [Release] Stage to Main 02/20
  .github/preview-index/README.md
  .github/preview-index/src/indexFull.js
  .github/preview-index/src/sharepoint.js
  .github/pull_request_template.md
  .github/workflows/merge-to-stage.js
  creativecloud/blocks/cc-forms/cc-forms.css
  creativecloud/blocks/unity/unity.js
  creativecloud/features/cc-forms/components/textfield.js
  creativecloud/features/cc-forms/forms/trials.js
  creativecloud/features/changeBg/changeBg.js
  creativecloud/scripts/utils.js
  libs/deps/README
  test/blocks/interactive-metadata/mocks/interactive-metadata.html
  test/features/firefly/mocks/body.html
  test/features/firefly/mocks/masonry-body.html
  web-test-runner.config.mjs
Labels: verified, ready for main

#630 MWPW-165929 Error message and dropdown values rendered is not seen re…
  creativecloud/features/cc-forms/components/checkbox.js
  creativecloud/features/cc-forms/components/dropdown.js
  creativecloud/features/cc-forms/components/textfield.js
Labels: verified, ready for stage

#651 MWPW-168482 | Update sidekick config json for hlx5
  tools/sidekick/config.json
Labels: verified, ready for stage

#586 MWPW-157950 | Migrating CC to unity V2 for performance and flexibility
  creativecloud/blocks/unity/unity.js
Labels: verified, ready for stage

#645 MWPW-165929 | Error message and dropdown values rendered is not seen retained in device , shown as flash and disappear
  creativecloud/features/cc-forms/components/checkbox.js
  creativecloud/features/cc-forms/components/dropdown.js
  creativecloud/features/cc-forms/components/textfield.js
Labels: verified, ready for stage

#648 MWPW-168400 | Updated pdf api clientId
  creativecloud/scripts/utils.js
Labels: verified, ready for stage

#652 MWPW-168392 | Interactive marquee CTA alignment.
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
Labels: verified, ready for stage

#658 Revert "MWPW-153103: creativecloud.adobe.com URLs not transforming during milo localization"
  creativecloud/scripts/utils.js
Labels: verified, ready for stage
