Repository adobecom/cc, pull requests merged in 2025-09, with the labels that each got.

#774 [MWPW-163836][Nonprofits] Express & CC Product of interest
  creativecloud/blocks/nonprofit/constants.js
  creativecloud/blocks/nonprofit/nonprofit.js
  test/blocks/nonprofit/mocks/body.html
Labels: verified, ready for stage

#778 [MWPW-175994] Consonant grid alignment
  creativecloud/blocks/upload/upload.css
Labels: verified, needs verification, High Priority

#785 [Release] Stage to Main 09/29
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
Labels: verified, ready for main
