Repository adobecom/cc, pull requests merged in 2025-05, with the labels that each got.

#709 [MWPW-171854] Fix - Demandbase popover not displayed correctly for 2-up sections
  creativecloud/blocks/cc-forms/cc-forms.css
  creativecloud/features/cc-forms/forms/demandbase.js
Labels: verified, ready for stage

#718 chore: Configure Trusted Hosts for Sidekick
  tools/sidekick/config.json
Labels: ready for stage

#729 MWPW-170275 & MWPW-171455 | Connect form treatmentid and purchase intent dropdown fix
  creativecloud/features/cc-forms/components/dropdown.js
  creativecloud/features/cc-forms/forms/connect.js
Labels: verified, ready for stage, verify on stage

#699 MWPW-168411 DALP Form migration | Unsubscribe variant
  creativecloud/blocks/cc-forms/cc-forms.css
  creativecloud/blocks/cc-forms/cc-forms.js
  creativecloud/features/cc-forms/components/checkbox.js
  creativecloud/features/cc-forms/forms/trials.js
  creativecloud/features/cc-forms/forms/unsubscribe.js
  test/features/cc-forms/forms/mocks/unsubscribe-body.html
  test/features/cc-forms/forms/unsubscribe.test.js
Labels: verified, ready for stage, verify on stage

#730 MWPW-172492: fixed multiple link text for a11y
  creativecloud/features/interactive-components/selector-tray/selector-tray.js
Labels: verified, ready for stage

#734 MWPW-173290 | Prevent dropdown arrow overlap with content for rtl locale
  creativecloud/blocks/cc-forms/cc-forms.css
Labels: verified, run-nala, ready for stage

#733 Fix(Mwpw-172064): Colour contrast of focus indicator adjusted(accessibility fix).
  creativecloud/blocks/interactive-metadata/interactive-metadata.css
Labels: verified, ready for stage, run-nala-on-cc

#732 MWPW-172494: Fixed Interactive Marquee - Purpose of link is not clear in context
  creativecloud/features/interactive-components/generate/generate.js
  creativecloud/features/interactive-components/start-over/start-over.js
Labels: verified, ready for stage

#737 MWPW-173695 and MWPW-173696 unsubscribe forms
  creativecloud/features/cc-forms/forms/unsubscribe.js
Labels: verified, ready for stage, verify on stage
